### ISSUE TITLE
[1.18.2] witchwater decays in barrel!

### ISSUE THREAD

**Issue by MSandro** [LordDeatHunter/FabricaeExNihilo#16] opened 2022-07-14 14:32 UTC
![image](https://user-images.githubusercontent.com/10937159/179007377-65f25ee3-01e3-40ee-ae3a-135a79fca555.png)
I can confirm this issue and have no idea why this is happening.

**Comment by MattiDragon** [comment] 2022-07-14 16:52
This is probably caused by the leaking feature. It happens when certain blocks are near the barrel and get converted.

Might be a good idea to remove it in the future. Could also be a bug with it

**Comment by salianifo** [comment] 2022-07-23 19:38
![2022-07-23_15 36 22](https://user-images.githubusercontent.com/2348534/180620403-c79d4605-199b-48ca-bc54-1ba562b14be9.png)
I saw this bug and though i should try using the stone barrel since it looks like in REI it's not supposed to leak, but I can confirm the same bug mentioned here. No surrounding blocks are actually converting either.

**Comment by 0gp** [comment] 2022-07-25 10:52
weird, I hope it can be fixed soon.

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 20:51
Perhaps it has something to do with not returning here?
https://github.com/LordDeatHunter/FabricaeExNihilo/blob/1.19/src/main/java/wraith/fabricaeexnihilo/modules/barrels/modes/FluidMode.java#L132

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 20:57
Also it seems fireproof variable is never requested by fluid mode.

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 21:19
latest 1.18 commit seems to work, unless adding a return for fireproof things only fixed it on non fireproof barrels

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 21:30
Yeah can't repro on latest commit
edit - nvm

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 21:48
Looks like it's somehow fixable by reloading and replacing barrel. Given I can do it once per load, I assume some variable is stored directly on the block and not in block state or on the entity. 
Able to repro on latest commit.

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 22:48
It only occurs when extracting via bucket or other item. This also affects milk to slime, for some reason, if you destroy the block instead of properly extracting. It then (somehow) switches to item mode with no item in it, and "extracting" does nothing

**Comment by TheDrawingCoder-Gamer** [comment] 2022-08-03 23:36
The issue is that you forget to copy the barrel mode before switching to alchemy mode. Creating a PR soon.

**Comment by LordDeatHunter** [comment] 2022-08-20 08:17
PR was merged, release coming soon.

**Closed as completed by LordDeatHunter** 2022-08-20 08:17 UTC
