### ISSUE TITLE
Crash when using Silkworms on 1.19

### ISSUE THREAD

**Issue by Matiam0** [LordDeatHunter/FabricaeExNihilo#10] opened 2022-06-20 19:28 UTC
**Versions**
_Minecraft: 1.19_
_Fabric: 0.14.7_
_Fabric API: 0.56.0_ 

**Description**
When using silkworms to infest leaves, everything seems normal until at the 99% mark, the game crashes with the following logs. Not 100% sure this is from FEN but as it only happens when using the worms figured I'd report it.

**Logs**
[Crash log](https://pastebin.com/4KAEdyZP)
[Latest.log](https://pastebin.com/cX6XeH49)

**Comment by LordDeatHunter** [comment] 2022-06-20 20:16
I'll give it a look in a minute, thanks for the report 👍
I would also recommend installing NotEnoughCrashes, since it both gives a clearer crash log, and sometimes prevents the game from fully crashing (brings you back to main menu in most cases).

**Comment by LordDeatHunter** [comment] 2022-06-20 20:42
I messed around with some of the mods you have installed, but I wasn't able to replicate the issue. It could some mod incompatibility. Would be great if you can provide new logs with NotEnoughCrashes installed.

**Comment by Matiam0** [comment] 2022-06-21 17:17
This is the latest [crash log](https://crashy.net/DyzR7dSPQL5h0xm0FO06) or [latest](https://pastebin.com/tgdcTL1Z) using NEC. I may attempt to do a clean re-install of Minecraft and my modsets. Using AdoptOpenJDK wouldn't have any affect would it?

**Comment by LordDeatHunter** [comment] 2022-06-21 18:43
The crash log link doesn't seem to work, it's either private or expired.
From the log, it looks like something isn't able to create leaf particles. I tried downloading a bunch of the rendering mods you had, but I wasn't able to replicate.
Can you maybe join the [discord](https://discord.gg/e5r7kuKRpY) and send your pack so I can test without having to download all the mods 1 by 1?

**Comment by Matiam0** [comment] 2022-06-23 09:58
Sorry it took me some time to get to it, I'll pack it up with the world, where would you like the link?

**Comment by LordDeatHunter** [comment] 2022-06-26 00:59
Seems like the problem is `Immersive Weathering`, I'll have to look into why. For now, check if there's anything for disabling the leaf particles.

**Comment by LordDeatHunter** [comment] 2022-06-26 01:12
Actually, it seems to have been fixed in the latest version of IW. Update both mods, and if you're still experiencing any issues regarding this, feel free to reopen the issue.

**Closed as completed by LordDeatHunter** 2022-06-26 01:12 UTC
